https://www.hackerrank.com/challenges/np-array-mathematics/problem?isFullScreen=true

In [8]:
import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)
print(a+b)
print(numpy.add(a,b))
print(a-b)
print(numpy.subtract(a,b))
print(a*b)
print(numpy.multiply(a,b))
print(a/b)
print(numpy.divide(a,b))
print(a%b)
print(numpy.mod(a,b))
print(a**b)
print(numpy.power(a,b))

[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [18]:
N, M = map(int, input().split())
a = []
b = []
for i in range(N):
    row = list(map(int, input().split()))
    a.append(row)
my_list = numpy.array((a))

for j in range(N):
    row = list(map(int, input().split()))
    b.append(row)
my_list = numpy.array((b))

print(numpy.add(a,b))
print(numpy.subtract(a,b))
print(numpy.multiply(a,b))
print(numpy.floor_divide(a,b)) # this is integer division and not regular divide
print(numpy.mod(a,b))
print(numpy.power(a,b))


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
