https://www.hackerrank.com/challenges/np-concatenate/problem?isFullScreen=true

In [1]:
import numpy


array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9])

print(numpy.concatenate((array_1, array_2, array_3)))

[1 2 3 4 5 6 7 8 9]


In [4]:
import numpy

array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]])

print(numpy.concatenate((array_1, array_2), axis = 1))

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


In [7]:
N, M, P  = map(int, input().split())
matrix1 = []
matrix2 = []
for _ in range(N):
    row = list(map(int, input().split()))
    matrix1.append(row)
my_list = numpy.array((matrix1))

for _ in range(M):
    row = list(map(int, input().split()))
    matrix2.append(row)
my_list = numpy.array((matrix2))


print(numpy.concatenate((matrix1, matrix2)))


[[1, 2], [1, 2], [1, 2], [1, 2]]
[[3, 4], [3, 4], [3, 4]]
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
