https://www.hackerrank.com/challenges/np-eye-and-identity/problem?isFullScreen=true

identity

The identity tool returns an identity array. An identity array is a square matrix with all the main diagonal elements as  and the rest as . The default type of elements is float.

In [1]:
import numpy
print(numpy.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


eye

The eye tool returns a 2-D array with 's as the diagonal and 's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter . A positive  is for the upper diagonal, a negative  is for the lower, and a   (default) is for the main diagonal.

In [4]:
import numpy
print(numpy.eye(8,7, k =3))

[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [7]:
import numpy
numpy.set_printoptions(legacy='1.13')
N, M = map(int, input().split())
print(numpy.eye(N,M))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
