https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem?isFullScreen=true

In [6]:
import numpy

# Floor
my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 10.9])
print(numpy.floor(my_array))

# Ceil
print(numpy.ceil(my_array))

# Rint - The rint tool rounds to the nearest integer of input element-wise.
print(numpy.rint(my_array))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10. 11.]


In [11]:
numpy.set_printoptions(legacy='1.13')
n = list(map(float, input().split()))
m = numpy.array(n)
print(numpy.floor(m))
print(numpy.ceil(m))
print(numpy.rint(m))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
