https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?isFullScreen=true

In [3]:
import numpy

print(numpy.zeros((1,2)))
print((numpy.zeros((1,2), dtype = int)))

[[0. 0.]]
[[0 0]]


In [5]:
print(numpy.ones((1,2)))
print(numpy.ones((1,2), dtype = int))

[[1. 1.]]
[[1 1]]


In [13]:
shape = tuple(map(int, input().split()))

print(numpy.zeros(shape, dtype=int))
print(numpy.ones(shape, dtype=int))

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
#  m , n , p = map(int, input().split()) # this limits the input to only 3 dimensions hence can not be used



In [14]:
shape = list(map(int, input().split()))

print(numpy.zeros(shape, dtype=int))
print(numpy.ones(shape, dtype=int))

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Performance: Tuples are slightly faster and use less memory than lists in Python because they are immutable (cannot be changed). However, for a small script like a HackerRank challenge, the difference is measured in nanoseconds—completely unnoticeable.